# Generated by Django 4.2 on 2025-01-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='price',
            field=models.TextField(default=11, verbose_name='価格'),
            preserve_default=False,
        ),
    ]
