# Generated by Django 4.0 on 2025-02-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freema', '0002_photopost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='price',
        ),
    ]
